### ISSUE TITLE
Tools not loading

### ISSUE THREAD

**Issue by jamesfalkner** [mark3labs/mcphost#72]
Using the latest mcphost (0.14.0), I have a config file that looks correct:

```yaml
mcpServers:
  mcp-atlassian:
    command: podman
    args: ["run", "-i", "--rm", "ghcr.io/sooperset/mcp-atlassian:latest", "--read-only", "--jira-url=https://[myJIRAserver]", "--jira-username=[MYUSERNAME]", "--jira-personal-token=[MYTOKEN]", "--jira-projects-filter=[MYFILTER]", "--verbose", "--enabled-tools=jira_get_issue,jira_search"]
```

But when I run mcphost with `--config ./config.yaml` it reports loading 0 tools:

```console
┃  Model loaded: ollama (qwen3:latest)
┃  MCPHost (18 Jun 2025 10:58 AM)

┃  Loaded 0 tools from MCP servers
┃  MCPHost (18 Jun 2025 10:58 AM)

┃ 🔧 Debug Configuration
┃   model: ollama:qwen3:latest
┃   max-tokens: 4096
┃   top-p: 0.95
┃   top-k: 40
┃   provider-url: [my provider url]
┃   num-gpu: 1
┃   main-gpu: 0
┃   provider-api-key: [SET]
┃   max-steps: 0
┃   temperature: 0.7
┃   system-prompt: ./sys.md
┃  MCPHost (18 Jun 2025 10:58 AM)
```

I believe my config file is correct. I have no ~/.mcp* files to confuse it. 

Also, if I pass `--config doesnotexist` mcphost seems to start up with no errors? even though there is no such file `doesnotexist`.
